include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
linter:
  rules:
    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Style
    prefer_single_quotes: false
    unnecessary_brace_in_string_interps: true
    
    # Safety
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_unnecessary_containers: true 